[Config]
Dependencies=
    rke2_confext
    rke2_sysext
    
[Build]
CacheDirectory=build/mkosi.CacheDirectory
BuildDirectory=build/mkosi.builddir
History=yes
BuildSourcesEphemeral=yes
Incremental=yes



[Output]
Format=none
OutputDirectory=build/mkosi.output