[Config]
Dependencies=base_dir

[Output]
Format=sysext
SplitArtifacts=no
Overlay=yes

[Content]
BaseTrees=%O/base_dir
ExtraTrees=
    %O/base_dir/usr:/usr
    %O/base_dir/opt:/opt
Packages=btrfs-progs
